# docker file to compile bash on ubuntu 18:04

from ubuntu:18.04
run apt-get update && apt-get install -y xinetd libssl1.0.0 netcat.openbsd wget curl nano file python
run apt-get install -y make gcc build-essential openssl libssl-dev git unzip
